{% set name = "labeling" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/labeling-{{ version }}.tar.gz
  sha256: eeb259932edda017527efb53ab6bcd28b60ed44d8cb7274cbe07a62376f9b28d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy <2
    - pillow <10
    - python >=3.6
    - tifffile
    - scipy <2

test:
  imports:
    - labeling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Labelings/pyLabeling
  summary: A package to create labeling/segmentation information based on pixel values.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomburke-rse
