{% set name = "labeling" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/labeling-{{ version }}.tar.gz
  sha256: 797389f825e88451feead379ec2c1327037daf2b64547882265652bcee3b113d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - pillow
    - python >=3.7
    - tifffile
    - scipy

test:
  imports:
    - labeling
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Labelings/pyLabeling
  summary: A package to create labeling/segmentation information based on pixel values.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomburke-rse
